export const events = [
  {
    id: "1",
    category: "Founder",
    cost: "$20.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Mira Karsgaard",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
    end_time: "6:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-09-25",
    start_time: "4:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['🚀 Open Space', '🧩 Strategy'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "2",
    category: "Expert",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Tatiana Press",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-10-13",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Each Other",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    // topics: ['🔍 User Research', '🌎 Social Impact'],
    topics: ['🔍 User Research'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "3",
    category: "Community",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Ziare Botosh",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-11-18",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['☕️ Action Cafe', '💵 Funding / Financial'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "4",
    category: "Founder",
    cost: "$20.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Mira Karsgaard",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
    end_time: "6:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-11-19",
    start_time: "4:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['🚀 Open Space', '🧩 Strategy'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "5",
    category: "Expert",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Tatiana Press",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-12-11",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    // topics: ['🔍 User Research', '🌎 Social Impact'],
    topics: ['🔍 User Research'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "6",
    category: "Community",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Ziare Botosh",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-12-22",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['☕️ Action Cafe', '💵 Funding / Financial'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "7",
    category: "Founder",
    cost: "$20.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Mira Karsgaard",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
    end_time: "6:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-12-23",
    start_time: "4:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['🚀 Open Space', '🧩 Strategy'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "8",
    category: "Expert",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Tatiana Press",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-12-27",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    // topics: ['🔍 User Research', '🌎 Social Impact'],
    topics: ['🔍 User Research'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  },
  {
    id: "9",
    category: "Community",
    cost: "$500.00",
    created_at: "2021-04-20 03:00:00",
    creator_name: "Ziare Botosh",
    custom_blurb: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec.",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
    end_time: "10:00 PM",
    location: "Online Event",
    logo: "https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F145050821%2F137717746968%2F1%2Foriginal.20210819-193830?h=200&w=450&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C0%2C2160%2C1080&s=4637bbc3cb7f162329726f2e7a91f1b2",
    start_date: "2021-12-29",
    start_time: "6:00 PM",
    title: "People and Power: Advancing Leadership",
    // We will want to account for title length. Perhaps append "..." after a certain number of characters for list view
    topics: ['☕️ Action Cafe', '💵 Funding / Financial'],
    url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
  }
]
// export const events = [
//   {
//     "category": "Founder",
//     "cost": "$20.00",
//     "created_at": "2021-04-20 03:00:00",
//     "creator_name": "Mira Karsgaard",
//     "description": "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
//     "end_time": "6:00",
//     "location": "Online Event",
//     "start_date": "2021-09-25",
//     "start_time": "4:00",
//     "title": "People and Power: Advancing Leadership",
//     "topics": ["🚀 Open Space", "🧩 Strategy"],
//     "url": "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     "category": "Expert",
//     "cost": "$500.00",
//     "created_at": "2021-04-20 03:00:00",
//     "creator_name": "Tatiana Press",
//     "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     "end_time": "10:00",
//     "location": "Online Event",
//     "start_date": "2021-10-13",
//     "start_time": "6:00",
//     "title": "People and Power: Advancing Each Other",
//     "topics": ["🔍 User Research"],
//     "url": "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     "category": "Community",
//     "cost": "$500.00",
//     "created_at": "2021-04-20 03:00:00",
//     "creator_name": "Ziare Botosh",
//     "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     "end_time": "10:00",
//     "location": "Online Event",
//     "start_date": "2021-11-18",
//     "start_time": "6:00",
//     "title": "People and Power: Advancing Leadership",
//     "topics": ["☕️ Action Cafe", "💵 Funding / Financial"],
//     "url": "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Founder",
//     cost: "$20.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Mira Karsgaard",
//     description: "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
//     end_time: "6:00",
//     location: "Online Event",
//     start_date: "2021-11-19",
//     start_time: "4:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["🚀 Open Space", "🧩 Strategy"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Expert",
//     cost: "$500.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Tatiana Press",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     end_time: "10:00",
//     location: "Online Event",
//     start_date: "2021-12-11",
//     start_time: "6:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["🔍 User Research"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Community",
//     cost: "$500.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Ziare Botosh",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     end_time: "10:00",
//     location: "Online Event",
//     start_date: "2021-12-22",
//     start_time: "6:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["☕️ Action Cafe", "💵 Funding / Financial"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Founder",
//     cost: "$20.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Mira Karsgaard",
//     description: "Product Hunt Showcase rooms are hosted at the end of everything month and will include some of the months successful Product Hunt launches.",
//     end_time: "6:00",
//     location: "Online Event",
//     start_date: "2021-12-23",
//     start_time: "4:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["🚀 Open Space", "🧩 Strategy"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Expert",
//     cost: "$500.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Tatiana Press",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     end_time: "10:00",
//     location: "Online Event",
//     start_date: "2021-12-27",
//     start_time: "6:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["🔍 User Research"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelelt"
//   },
//   {
//     category: "Community",
//     cost: "$500.00",
//     created_at: "2021-04-20 03:00:00",
//     creator_name: "Ziare Botosh",
//     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec metus congue, facilisis odio vel, eleifend dolor. Morbi ut mattis quam. Interdum et malesuada fames.",
//     end_time: "10:00",
//     location: "Online Event",
//     start_date: "2021-12-29",
//     start_time: "6:00",
//     title: "People and Power: Advancing Leadership",
//     topics: ["☕️ Action Cafe", "💵 Funding / Financial"],
//     url: "https://www.eventbrite.com/e/product-hunt-showcase-tickets-167770920339?aff=erelexpmlt"
//   }
// ]