import NewEvent from "./NewEvent.d";

export const emptyEvent: NewEvent = {
  logo: '',
  category: '',
  category_text: '',
  changed: '',
  cost: '',
  currency: '',
  created_at: '',
  creator_name: '',
  creator_email: '',
  custom_blurb: '',
  // id: '',
  location: '',
  // name: '',
  organizer: '',
  promoted: false,
  series_dates: [],
  start: '',
  end: '',
  start_date: '',
  end_date: '',
  start_time: '',
  end_time: '',
  summary: '',
  title: '',
  url: null,
};
