import NewEvent from "./NewEvent.d";

export const emptyEvent: NewEvent = {
  logo: '',
  category: '',
  category_text: '',
  changed: '',
  cost: '',
  currency: '',
  created: '',
  creator_name: '',
  creator_email: '',
  description: '',
  id: '',
  location: '',
  name: '',
  promoted: false,
  series_dates: [],
  start: {},
  end: {},
  start_date: '',
  end_date: '',
  start_time: '',
  end_time: '',
  summary: '',
  title: '',
  url: null,
};
